# Generated by Django 3.1 on 2020-09-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(default='', max_length=500)),
                ('slider_image_1', models.ImageField(default='', upload_to='images')),
                ('slider_image_2', models.ImageField(default='', upload_to='images')),
                ('slider_image_3', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
