# Generated by Django 3.1 on 2020-09-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
