# Generated by Django 3.1 on 2020-09-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200916_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='main_image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
