# Generated by Django 3.1 on 2020-09-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designs',
            name='design_image',
            field=models.ImageField(default='', upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='designs',
            name='design_specs',
            field=models.FileField(upload_to='media/pdf'),
        ),
    ]
