# Generated by Django 3.1 on 2020-09-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_auto_20200909_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designs',
            name='design_image',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='designs',
            name='design_specs',
            field=models.FileField(upload_to='pdf'),
        ),
    ]
