# Generated by Django 3.1 on 2020-09-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='', max_length=50)),
                ('project_desc', models.TextField(default='')),
                ('project_main_image', models.ImageField(default='', upload_to='images')),
                ('project_status', models.BooleanField(default=False)),
                ('project_specs', models.FileField(upload_to='pdf')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
