# Generated by Django 3.1 on 2020-09-10 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_projects_project_sub_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('image_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.projects')),
            ],
        ),
    ]
