# Generated by Django 3.1 on 2020-09-10 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_projectimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_sub_images',
        ),
    ]
