# Generated by Django 3.1 on 2020-09-08 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('contact_number', models.CharField(default='', max_length=13)),
                ('message', models.TextField(default='')),
                ('sent_on', models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 21, 10, 29, 976303))),
            ],
            options={
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
