# Generated by Django 3.1 on 2020-09-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(default='', max_length=50)),
                ('member_bio', models.TextField()),
                ('member_image', models.ImageField(default='', upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
