# Generated by Django 3.1 on 2020-09-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='member_position',
            field=models.CharField(default='', max_length=20),
        ),
    ]
